MatrixPilot/flightplan.c, MatrixPilot/telemetry.c, Tools/MatrixPilot-SIL/Makefile.unix
Thanks to Giulio Berti for suggesting this improvement in the[ uavdevboard-dev thread.](https://groups.google.com/d/msg/uavdevboard-dev/osH_9e0pd6M/qcj1AhrQAwAJ)
I have regrouped the voltage, amp and amp hours to be in the same part of the telemetry file.
I have dropped support for voltage_milis.BB in SUE. I don't believe anyone has been using that.
Giulio, please can you try this out, and test it in your flights, and confirm that it is working for you before I move this pull request into Master.
=> Improve support in for battery voltage and power monitoring 

MatrixPilot/flightplan-logo.c
This issue came to light with Giulio Berti testing his flying wing with Master. The full discussion can be seen from here [on this thread.](https://groups.google.com/d/msg/uavdevboard/BZe_GGs0b8A/vvn9tCv3AwAJ).
F_ALTITUDE_GOAL is a flag that can set both in waypoints.h and flightplan-logo.h . It is meant to provide a mechanism of moving onto another waypoint as soon as a given altitude is reached. For example, you could takeoff, and give the plane a waypoint a mile away in one direction. And you could request an altitude of 100 meters. As soon as the plane reaches 100 meters, with F_ALTITUDE_GOAL set, the plane will move onto the next waypoint, and ignore the current waypoint (which is probably still nearly a mile away).
In flightplan-logo.c, once the goal is reached, the behaviour flag …
=> Fix Logo's processing of  F_ALTITUDE_GOAL

MatrixPilot/telemetry.c
A simple fix to ensure the F2: statement in SERIAL_UDB_EXTRA does not initially print 1/2 of it's line at the start of the telemetry file; but waits until all the other initialisation telemetry has completed, before it starts printing whole F2 lines. Ground Tested on the UDB4.
=> Fix initialisation of SERIAL_UDB_EXTRA  (SUE)

libUDB/interrupt.h
As[ discussed recently in uavdevboard](https://groups.google.com/d/msg/uavdevboard/Ja-NeeXkC50/vHyuhmoLAwAJ) I am moving to have USE_MCU_IDLE be switched off i.e. move from being 1 to 0.
=> Change default of USE_MCU_IDLE from 1 to 0 .

MatrixPilot/altitudeCntrlVariable.c, MatrixPilot/defines.h, MatrixPilot/helicalTurnCntrl.c
if one or more of these setting are used, compilation errors may occur, and/or code will not function;
GAINS_VARIABLE                      1
ALTITUDE_GAINS_VARIABLE             1
GLIDE_AIRSPEED_CONTROL  1
fixing this may help to fix SPEED_CONTROL as well.
Best regards,
Kees
=> Glide airspeed control fix

MatrixPilot/MAVLink.c
In response to [the issue I opened](https://github.com/MatrixPilot/MatrixPilot/issues/18), I propose a possible solution.
The VFR_HUD message includes the climb rate in m/s as float value, while we are currently sending (-IMUvelocityz._.W1) in cm/s.
I've only compiled this change, I'll test it tomorrow.
Best regards,
Giulio
=> Corrected the climb rate scaling from cm/s to m/s in Mavlink VFR_HUD message

MatrixPilot/MAVLink.c
As I started to use the Minim Osd, flashed with MinimOsdExtra firmware, I noticed that voltage and current data were not displayed, even though I had already configured the voltage and current sensor in options.h
I wanted to fix this also to learn the GitHub workflow, explained by Pete in [one of his videos](https://vimeo.com/163824531).
For the time being, I've only compiled this fix, I'll fly test it tomorrow.
Personally, I find that the use of #if () #else #endif disrupts the readability of the code, but I understand the memory efficiency needs.
Best regards,
Giulio
=> Include battery Voltage and Current in the Mavlink SYS_STATUS mesage

MatrixPilot/servoPrepare.c
After some [discussion on CPU load](https://groups.google.com/d/msg/uavdevboard/xWHRCKIFewQ/M4FHbYnJBAAJ), and the fact that for the UDB5 and AUAV4 HEARTBEAT is driven at 200Hz by the invensense gyro, and so the flight_controller() routines should be limited to running at 40Hz. In the past, they were not, and so were running at 200Hz and chewing up CPU.
This Pull request compiles, and CPU has returned from 26% before the commit,  to 20% (In line with the original wjp_helicalTurns branch).  (That is a start up figure).
The Pull request needs flight testing. Volunteers ?
=> Limit main routine in flight_controller() to running at 40Hz.

Tools/UDB_Logo_Editor/udb_logo_editor.html, Tools/Waypoint_Editor/udb_waypoints.html
- Updated the URLs for markers to use the GitHub-hosted copy from
googlemaps rather than the (deprecated) GoogleCode URLs.
- Changed the reference to the plane image (plane.png) to use the local
file, which prevents having to update when the project hosting changes.
- Fixed the reference link to point to the GitHub-hosted MatrixPilot
=> Update logo and waypoint editor tools to fix broken links (images)

MatrixPilot/helicalTurnCntrl.c
MINIMUM_AIRSPEED was used in airspeed_options.h and in helicalTurnCntrl.c in two different contexts, with two different values. 
The compiler was warning that MINIMUM_AIRSPEED was being re-defined. 
This is a small fix for that.
=> Fix use of MINIMUM_AIRSPEED in two different contexts.

Tools/FlashOSD/main.c, libUDB/ConfigUDB4.h
This fix does not include the change required to the configuration of the pre-processor options in MLAB or MPLAB-x which is to add an include directory of "../../../Config" (Parent ..s are three levels up).
But with that addition, and these changes the code compiles but has a warning ...
../../../libUDB/heartbeat.c: In function 'heartbeat_pulse':
../../../libUDB/heartbeat.c:121:2: warning: implicit declaration of function 'udb_callback_read_sensors'
Ideally, a developer with working knowledge of the OSD toolkit, and working hardware, would check this out for Ric. who setting up his plane of FPV work.
=> Fixes to improve compilation of FlashOSD tool

libUDB/heartbeat.c, libUDB/mcu.c
I would like to remove all warnings from a default compile of the code.
Out of the box, a download of master, should compile without warnings in my view.
=> Reduce warnings from a default compile

MatrixPilot/telemetry.c
UDB4 Z gyros can change significantly for some bootups. 
We are now using CUSTOM_OFFSETS and need to reasonably sure that they are close to the seen sensor values. 
It seems sensible to monitor this in the telemetry.  The telemetry will capture the actual offsets (whether they are CUSTOM_OFFSETS or not) and print out the instantaneous value of the sensors (allowing for gravity on Z accelerometer) at the time of the telemetry being output (which starts just after calibration).
Here is some example telemetry:-
F21:Sensors=903,113,-1812,-5758,-6223,-6408
F20:Offsets=832,22,-1759,-5762,-6222,-6412
F15:IDA=Alpha Axion 139 3X MP:IDB=AA-PDH-UK-UDB-STACK:
F16:IDC=Pete Hollands:IDD=http://www.diydrones.com/profile/PeterHollands:
The sensor outputs are in the order:
X accel, Y accel, Z accel, X …
=> Record sensor offsets and typical values in SERIAL_UDB_EXTRA telemetry

libUDB/heartbeat.c
fix to reduce the sample frequency for analog inputs following the change in HEARTBEAT_HZ (r1172).
- r1155 (abstract the flightplan handler) crippled LOGO. Available modes where manual, stabilized, and manual.
I reported this before: https://groups.google.com/forum/#!topic/uavdevboard/dKxv509p060, apr 16.
I have not tested FP_WAYPOINTS
- the analog fix adresses that after the change form  HEARTBEAT_HZ=40 to HEARTBEAT_HZ=200 for Udb5 and Auav3,  heartbeat_pulse(void) is run at 200Hz.
This leaves too little time for analog samples to be completed. The fix brings te sample rate back to 40Hz. I only tested this on a Auav3 board.
without the fix, the first sample is correct, but no updates follow. This can easily go unnoticed. So testing should be done by changing the applied voltage …
=> reduce the sample frequency for analog inputs following the change in HEARTBEAT_HZ (r1172).

libDCM/libDCM.c, libDCM/libDCM.h, libUDB/ADchannel.c, libUDB/analog2digital_udb4.c, libUDB/heartbeat.c
Initialise UDB4 Gyros with Auto_Zero feature, just before the DCM offset calibration, about 9 seconds after bootup. There is no use delay functions in this code.
CUSTOM_OFFSETS are not used for the Gyros of the UDB4. Testing had shown that UDB4 gyros could power up with different offset values. Other boards (e.g. UDB5 and AUAV3) continue to use CUSTOM_OFFSETS on their gyros.
This version of the code uses auto-zero timing relative to CALIB_COUNT (now called DCM_CALIB_COUNT) in the dcm routine for recording offsets.
=> Background UDB Gyro Initialisation

libUDB/mcu.c
This commit ensures that a Null Character is not present at the start of every OpenLog File when using the AUAV3.
The original code for the AUAV3, setup the Input and Output pins of the UART as part of the configuration subroutine, configureDigitalIO(void). However,in the reference manual, and UART chapter for this processor, it explains that the pins will be setup when the UART peripheral module is enabled. That will happen automatically at that time.
So the old code setup the pins twice. Once in configureDigitalIO and once when the UART module was enabled. The result was that a Null Character (ascii value \000) was sent down the TX stream.
=> AUAV3: Stop Null char  at start of telemetry and GPS UART transmit streams.

libUDB/analog2digital_auav3.c, libUDB/analog2digital_udb4.c
There have been some #warnings messages in the analog2digital.c files that have not been working for some time. 
I am also moving a a default compile of MatrixPilot and RollPitchYaw that produce no warnings; i.e. a totally clean compile. This makes it much easier to see unusual events in the compile output.
So I have removed the SELECT_VALUE warning messages from analog2digital.c .
=> Reduce spurious warnings on a default compile - SELECTED_VALUE

MatrixPilot/config.c, MatrixPilot/minIni.c, MatrixPilot/minIni.h
2nd Try:-
This change is being made to remove a compiler warning in the project that ini_read() and ini_rename are being defined but not used.
Here is what was happening:-
minIni.c  includes miniIni.h which, in turn, includes minGlue-mdd.h. 
minGlue_mdd.h has two statically defined functions called ini_read() and ini_rename.
This all works fine for minIni.c which uses ini_read() and ini_rename().
However, config.c, also includes minIni.h, but will never directly use ini_read() and ini_rename(). Because these functions are are statically defined, they are separately instantiated inside of config.c (in a separate name space), and so are created inside of config.c and never used.
This commit, ensures that the statically defined functions [ini_read(), ini_rename()] are not defined in config.c …
=> Prevent compiler warning that ini_read() and ini_rename() but not used 

libUDB/mcu.c
About 1 to 2 times in every 10 times, the telemetry from the AUAV3 to the OpenLog was not starting. Extensive investigations showed that TX interrupt handler was firing and placing chars in the FIFO queue, but a logic analyser showed absolutely no bits were coming from the telemetry UART.
Looking for differences between the AUAV3 and other boards, I noted that the clock of the AUV3 was setup differently when using the XC16 compiler. This non startup fault of the telemetry seems to have only been noticed by myself and Kees who use the MPLAB-X XC16 compiler. The code that sets up the clock for the AUAV3 has different clock settings when using the XC16 compiler. 
I compiled master under the old MPLAB and C30 compiler, under Windows,  and in 50 tests, there were no faults in starting up the …
=> AUAV3: Prevent intermittent non-startup of telemetry.

libUDB/mcu.c
Warnings are no longer generated concerning use of deprecated syntax.
=> Use new XC16 compiler syntax to setup up processor configuration bit.

Config/options.h, MatrixPilot/config.c, MatrixPilot/config.h, MatrixPilot/helicalTurnCntrl.c, MatrixPilot/parameter_table.c, MatrixPilot/parameter_table2.c, MatrixPilot/telemetry.c
I would prefer to use REFERENCE_SPEED in options.h as the speed at which the parameters for Angle of Attack and Trim are nominally calculated. "CRUISE_SPEED"  may be confused with some concept of the desired cruise speed. There is a DESIRED_SPEED further up the options.h file, and I want to make the link between this parameter and the Angle of Attack and Trim parameters stronger.
=> Refactor CRUISE_SPEED to be REFERENCE_SPEED across MatrixPilot.

Config/options.h
Just a commit to provide a place holder for CUSTOM_OFFSETS in the options.h file.
I have put it close to the Angle of Attack and Trim parameter settings, as CUSTOM_OFFSETS are usually required if using that facility.
=> Add CUSTOM_OFFSETS to options.h file.

Tools/makefiles/toolchain-XC16.mk, build-all.sh
This is a small but significant fix for the X16 compiler options when using the build-all.sh script to generate multiple  hex images for multiple target architectures (UDB4, UDB5, AUAV3 and SIL).
The script was failing to link correctly before this commit.
=> Fix linker/loader flag in X16 toolchain makefile

libDCM/gpsParseUBX.c
Kees,
This is a fix for #59 .
payloadlength is a signed integer in the[ ublox code file.](https://github.com/MatrixPilot/MatrixPilot/blob/master/libDCM/gpsParseUBX.c#L40)
I had to change [both variables in the printf](https://github.com/MatrixPilot/MatrixPilot/blob/master/libDCM/gpsParseUBX.c#L628) statement to remove the warning.
=> Fix warning from compiler when using HILSIM from Ublox Parser.

Config/options.h, MatrixPilot/console.c, MatrixPilot/navigate.c, libDCM/estAltitude.c, libDCM/estLocation.c, libDCM/libDCM.c, libUDB/barometer.c
This aims to make configuring barometer easier. This means that enabling but not using barometric pressure is no longer possible.
rename  BAROMETER_ALTITUDE to USE_BAROMETER_ALTITUDE;
the macro BAROMETER_ALTITUDE might suggest an altitude value is configured, which is not the case
USE_BAROMETER_ALTITUDE makes clear this is a 0/1 setting.
remove #define USE_PRESSURE_ALT because it is not obvious that is should be commented out, not set 0 to inactivate.
also, a commented line would need to be added to indicate how to enable it, we don't like that.
LAUNCH_ALTITUDE is not needed anymore, because it is read from GPS automatically when the calibrations are performed (double waggle)
=> Simplify barometer configuration

MatrixPilot/telemetry.c, Tools/flight_analyzer/flan.pyw, Tools/flight_analyzer/matrixpilot_lib.py
and add desired height to csv file produced by flight analyzer (flan.pyw).
This feature will allow Leo to display the setpoint of commanded altitude from the throttle channel, on the overlay of his video using Dashware.  I also enclose a sample graph from libreOffice showing the relationship between IMU Z altitude and desiredHeight from a flight today.
I am wary of adding data to the SERIAL_UDB_EXTRA F2: format statement, as on older cards, the time to store data on the memory card can allow the OpenLog buffer to overrun (no flow control). So I'm open to suggestions whether we go ahead with this change. It works on my OpenLog at 57600 baud.
=> Add desiredHeight to SERIAL_UDB_EXTRA telemetry,

MatrixPilot/airspeedCntrl.c
brakes never get completely released after overspeed has been resolved.
=> overspeed fix:

MatrixPilot/servoPrepare.c, MatrixPilot/states.c, MatrixPilot/telemetry.c, Tools/MatrixPilot-SIL/SIL-udb.c, libDCM/libDCM.c, libUDB/heartbeat.c, libUDB/heartbeat.h
Split udb_heartbeat_counter and create udb_pulse_counter for low priority heartbeat.
This is a fix for issue #75 in which activating the OSD with the UDB5 using SPI bit bashing, when using the UDB5, would result in the GPS (EM506 or Ublox) not getting initialised correctly. It is expected that the issue also effected the AUAV3 because they both use a 200HZ Heartbeat, unlike the UDB4 which uses a 40HZ heartbeat.
The root cause was that udb_heartbeat_counter was incremented in a high priority interrupt (heartbeat()), but was being used in a low priority interrupt (heartbeat_pulse). If heartbeat_pulse took more than 1/200th of a second to complete, then udb_heartbeat_counter could get incremented while heartbeat_pulse() was part of the way through processing it's routines. See issue #75 for …
=> Fix GPS initialisation when OSD SPI bitbash used with AUAV3 or UDB5,

Config/options.h, MatrixPilot/telemetry.c, libUDB/magnetometer.c, libUDB/magnetometer.h
Before starting on SUE over MAVLink, I would like to tidy up telemetry.c, mainly because it is hard to read with so many #if statement to include or exclude code.
I have taken out SERIAL_UDB as I am only aware of people using SERIAL_UDB_EXTRA. 
I have taken out SERIAL_UDB_MAG, as debugging of the magnetometer is usually done with SERIAL_MAGNETOMETER. 
SERIAL_MAGNETOMTER was printing out a variable called I2ERROR. If anyone can point me to where I2ERROR is defined, I would be grateful, as I cannot currently declare it correctly, and so have temporarily commented it out. 
I have some testing to do on this, but thought I would put these ideas past you all, before I go too far, if I need to back off.
=> Telemetry.c tidy up

Tools/UDB_Logo_Editor/udb_logo_editor.html
Fix reference to flightplan-logo.h in UDB LOGO editor to the new config directory
=> Fix reference to flightplan-logo.h in UDB LOGO editor

MatrixPilot/mp_osd.c, MatrixPilot/osd_layout.h
Just a blinking alarm on low RSSI in the native OSD
[Video for the new feature](https://youtu.be/rVJ379R7bZ0)
=> RSSI signal, in OSD, will blink when the signal strenght drops below a configurable value

Config/Grobularis/options.h, Config/Grobularis/options_airspeed.h, Config/Grobularis/options_mavlink.h, Tools/ProjGen/proj_gen.bat
Hi,
This one is a response to Roberts requests for configurations.
https://groups.google.com/forum/#!topic/uavdevboard/jSC78Ly8qEg
Robert,
Thanks very much for this possibility. It will be reassuring, knowing Travis will look at all the new pull requests, testing them with MP features, some of which 
that are not used by many users. I would like submit the Grobularis configuration for Hilsim. This X-plane rc-model was created by Matt Coleman. 
It supports motor, flaps and ailerons.  
This config also allows for easy setup and testing of e-glider and glider aircraft, and as a starting point for anyone who wants to try AIRFRAME_GLIDER, GLIDE_AIRSPEED_CONTROL and other related features.
Here's a list of the features:
BOARD_ORIENTATION                   ORIENTATION_BACKWARDS
AIRFRAME_TYPE …
=> Grobularis config

libUDB/builtins.h
Rob, this one is for your to review and approve please. 
The decision on whether to include builtins.h (based on target processor architecture)  is made in[ udbTypes.h at this location.](https://github.com/MatrixPilot/MatrixPilot/blob/master/libUDB/udbTypes.h#L44)
=> Make clear that builtins.h macro file is not used with dspic devices.

Tools/MatrixPilot-SIL/UDBSocketUnix.c
This module is used by three targets: MatixPilot-SIL, HILSIM-XPlane and silcat.
Propose the next change to be making all three targets depend on a single copy of the UDBSocket* modules, such as in a new path Tools/UDBSocket/.
=> Covscan fixes 3

libDCM/mathlibNAV.c
An improvement to rotate_2D(). The fix ensures that rounding is effectively done between -0.49 to +0.5 rather than from 0,0 to 1.0. So this fix can remove a small bias in some calculations.
=> mathlibNAV.c: Improve rounding in rotate_2D()

Tools/flight_analyzer/flan.pyw
I have added a column called GPS Alt AO, meaning GPS Altitude Above Origin. This is useful when graphing Desired Height against achieved height (GPS Alt AO) in tools like Dashware and Racerender which overlay graphs and gauges from the telemetry onto video. In the screenshot blow, you can instantly see that at the start of my telemetry, the GPS is already reading 5 meters above the origin, even though the aircraft has not yet taken off.
I have also ensured that all velocities in the csv file are now consistently in meters / second (floating point to two decimal places).
=> Flight Analyzer CSV file  improvements

MatrixPilot/MAVLink.c, Tools/makefiles/target-MatrixPilot.mk
Invert the logic of the make conditional so the default build appears first. Project generator does not interpret the conditional and therefore I broke it when I added support for the PX4 target.
=> Proj gen fix

MatrixPilot/MatrixPilot-auav3.X/nbproject/configurations.xml, MatrixPilot/MatrixPilot-udb4.X/nbproject/configurations.xml, MatrixPilot/MatrixPilot-udb5.X/nbproject/configurations.xml, RollPitchYaw/RollPitchYaw-auav3.X/nbproject/configurations.xml, RollPitchYaw/RollPitchYaw-udb4.X/nbproject/configurations.xml, RollPitchYaw/RollPitchYaw-udb5.X/nbproject/configurations.xml, Tools/FlashOSD/FlashOSD-auav3.X/nbproject/configurations.xml, Tools/FlashOSD/FlashOSD-udb4.X/nbproject/configurations.xml, Tools/FlashOSD/FlashOSD-udb5.X/nbproject/configurations.xml, Tools/LedTest/LedTest-auav3.X/nbproject/configurations.xml, Tools/LedTest/LedTest-udb4.X/nbproject/configurations.xml, Tools/LedTest/LedTest-udb5.X/nbproject/configurations.xml, libFlashFS/AT45D_DMA.c, libUDB/I2C1.c, libUDB/I2C2.c, libUDB/analog2digital_auav3.c, libUDB/analog2digital_udb4.c, libUDB/analog2digital_udb5.c, libUDB/background.c, libUDB/events.c, libUDB/interrupt.h, libUDB/mpu_spi.c, libUDB/radioIn.c, libUDB/serialIO.c, libUDB/servoOut.c, libUDB/servoOutPins.h, libUDB/sonarIn.c
For many years, I've wanted to be able to see the millisecond level interaction of the various interrupt routines in MatrixPilot. This block of code has let me view the interactions between interrupts in much greater detail.  I enclose  example screenshots below using the Salae Logic Analyser.
The first screenshot shows a 1 second overview. The GPS data is arriving at 4HZ (HILSIM UDB4). 
In the second screenshot, a close up on the arrival of the 1st GPS block of data,  you can see the GPS navigation thread being interrupted by the DCM thread, so that the GPS thread does not complete until after the DCM thread has completed.
I am going to test this code in more detail before merging (especially for the AUAV3), but I would like to leave the code here in this pull request for a few days, to …
=> Interrupt priority analysis

libDCM/libDCM.c, libUDB/I2C2.c, libUDB/barometer.c, libUDB/barometer.h, libUDB/magnetometer.c, libUDB/magnetometer.h
The goal is to allow the Barometer and Magnetometer to reliably work together while sharing the same I2C2 bus (2 wires).
Once calibrated the Magnetometer state machine can return new data from the sensor with one call. But the Barometer state machine expects 6 calls to return the temperature and pressure. We intend to retrieve useful sensor data from each device bat 4Hz. 
It is not possible to just toggle calls between each device, as sometimes, it is essential that one device is called up to 6 times consecutively, for each of the next 40Hz frames. Rob had a good go at this, but I have really taken his ideas further.  I have modified the rxBarometer() and rxMagnetometer() routines so that they return a state as to whether they needs servicing imminently again. If they do, then they will …
=> I2C2 improvements to use mag and barometer together

Config/options.h, Config/options_magnetometer.h, MatrixPilot/defines.h, MatrixPilot/telemetry.c, libUDB/magnetometer.c, libUDB/magnetometer.h
In order to test the AUAV3 with both barometer and magnetometer running on the I2C bus, I needed to get the HMC5883L running correctly.  I did this eventually by setting up static offsets, and switching off the automatic calibration of offsets in the magnetometer. My hypothesis is that the HMC5883L has larger offsets than the original HMC5843 which Bill used when developing automatic calibration, and so it is either too slow or does not work on the HMC5883L. I tidied up some of the code for Static Offsets, and have added a new printout feature (SERIAL_MAG_CALIBRATE) for measuring the offsets in the telemetry. After carefully running that facility, and creating graphs in the corresponding csv file, I now have a pretty good round and centred sphere of measurements from the HMC5883L.  Ground …
=> Static mag offsets2

build-all.sh
At the moment, if the script build-all.sh has an error in the make of one of it's many configuration scenarios, it will report the error in the log, but Travis will still believe that the entire session ran smoothly.
I have edited the script, so that any one single failure will result in a Fail being returned to the caller of build-all.sh (Travis). I have tested it outside of Travis.
At the moment, the SIL configuration and one of the other configuration are commented out, as they are failing anyway. I will look at how to fix the up, and then put in a separate Pull Requests for those fixes. 
I did look at make a subroutine called "try()" which would keep track of whether a given command line had been successful. However I ran into the difficulties of borne shell evaluation of quotes with …
=> Fix build all sh script to return "pass" or "fail" of session to Travis 

Config/Cessna/options_magnetometer.h, RollPitchYaw/Config/options_magnetometer.h, Tools/FlashOSD/Config/options_magnetometer.h, Tools/LedTest/Config/options_magnetometer.h, Tools/MatrixPilot-SIL/SIL-udb.c
This PR updates the options_magnetometer.h file of non MatrixPilot Projects (e.g. RollPitchYaw etc) with MAG_STATIC_OFFSETS. They will fail to compile in MatrixPilot_5_0_1. Apologies.  I will have to bump the new release with this PR to MatrixPilot_5_0_2 and let uavdevboard group know. If anyone notices anything else of high priority that needs fixing please let me know.
Thanks to Robert for spotting the issue in the build log files. The Travis build system will need fixing so that it actually reports this type of error correctly back up to the main page.
=> Add MAG_STATIC_OFFSETS to RollPitchYaw, FlashOSD, LedTest and  Cessna Projects

libDCM/rmat.c, libDCM/rmat.h
gplane[] has had two meaning in the code, depending on the timing of when you view it in the DCM thread of activity. The 1st meaning was to be the  (gravity - acceleration) in the body frame (the plane's frame). This 1st meaning was used as the basis of measurement for DeadReckoning. Later in the code, the gplane variable is re-used for a second meaning,  to find the gravity vector. This made for some confusing reading for new users to the code. So I've refactored the 2nd meaning have a new variable called gravity_vector_plane[].
=> refactor gplane[] into two: gplane[] and gravity_vector_plane[]

MatrixPilot/telemetry.c, libUDB/serialIO.c, libUDB/serialIO.h
This is a potential fix to the telemetry bug #108  seen when using 1 Megabaud rates from MatrixPilot and using SERIAL_UDB_EXTRA.
=> Fix high speed baud rate (1 megabit) telemetry bug

libUDB/heartbeat.c, libUDB/radioIn.c, libUDB/radioIn.h
In approving Bill's recent change to radioIn failsafe,  I found the names of the variables and one of the routines to be confusing. So I've changed some of the names to make the code easier to read. There are no functional changes.
=> A refactoring of radioIn failsafe for easier code review. No functional changes.

libUDB/analog2digital_udb5.c
use Mark Whitehorn's timing constants to reduce CPU loading.
=> Reduce CPU Loading by revision of A/D for UDB5. 

libDCM/deadReckoning.c, libDCM/estLocation.c
GPS latency adjustments are best not applied during HILSIM, when there is no latency in calculating the GPS position inside of the X-Plane simulator. There is some latency in transmitting the position from X-Plane 10 via 38400 serial comms to the uavdevboard, but this is much less than with a real GPS.
This PR also re-instates the calculation of airspeed in HILSIM to be done in the same way as in a real flight.
=> Hilsim:- delete latency adjustment

MatrixPilot/telemetry.c, Tools/flight_analyzer/flan.pyw, Tools/flight_analyzer/matrixpilot_lib.py, libDCM/gpsParseCommon.c, libDCM/gpsParseCommon.h, libDCM/gpsParseSTD.c, libDCM/gpsParseUBX.c
Bill has added code to the GNSS parsers for the EM406/506 and Ublox, to check if there are problems parsing the serial stream from the receiver units.  This then showed that The Ublox parser was having 8 errors in normal operations at startup. That turned out to be caused by the ACK / NACK messages not having proper logic for obtaining their checksum, and so that is also fixed in this PR.
A new SERIAL_UDB_EXTRA (SUE) format message F23:) is now printed after each F2 telemetry line, which contains the count of gps parse errors. The intention is that future new telemetry for SUE will be added  to the F23: message from now on, and not to the F2: message. This solves a problem with MAVLink compatibility, in that our F2: message cannot be changed in Mavlink, as it has been formerly published. …
=> Keep track of GNSS parse errors in the telemetry; Flan  warns users if errors are present

MatrixPilot/telemetry.c, Tools/MatrixPilot-SIL/SIL-serial.c
This PR is primarily to allow discussion between Pete and Rob regarding the telemetry comms architecture, and getting SILSIM working.
The immediate background here is that Ric needs to test fairly complex Logo routines. One of the fastest and most reliable methods for testing Logo is with SILSIM. It is fast to compile a new change (just over 2 seconds on my machine), and X-Plane 10, can be left running during the process. So a quick change of Logo routine to testing it in flight, is just a matter of a few seconds.
So my main immediate goal is to get the SERIAL_UDB_EXTRA telemetry working in SILSIM immediately.
Beyond that, I can see that Rob has been working diligently on trying to improve and rationalise our comms architecture. 
Rob, perhaps you could review what I've done this morning …
=> SILSIM: re-code for SUE telemetry to work.

Config/Cessna/options.h, Config/CloudsFly/options.h, Config/E_Glider/options.h, Config/Grobularis/options.h, Config/options.h, MatrixPilot/states.c, MatrixPilot/telemetry.c, RollPitchYaw/Config/options.h, libDCM/gpsData.c, libDCM/gpsParseCommon.c, libDCM/gpsParseCommon.h, libDCM/gpsParseUBX.c
This PR is primarily for people that fly in places where the GNSS accuracy may be obscured by mountains and buildings. It has two features:-
- The user can specify that the "GPS Acquired" state does not occur until the following metrics are met:-
o  HDOP exceeds a value set in options.h
o SVS exceed as value set in options.h
o And for the Ublox only, VDOP exceeds a value set in options.h
The usual standby by timer is also in effect, so the GNSS device always has to settle down for a period before "GPS iacquired."
- The VDOP values are now embedded in the SERIAL_UDB_EXTRA telemetry. This will help us to measure whether VDOP is significantly effected when the plane is low down in Alpine valleys, with mountains high all around.
I have started to test the scheme, and I invite comments from …
=> GNSS (Global Navigation Sattelite System) metrics

libUDB/builtins.h
Rob, 
I changed the builtins.h file (which only is used for non dspic devices) this morning to better reflect my understanding of the size of the integers required for each of the parameters, and also the size of the returned values.  Fly By Wire Mode is now running correctly in SILSIM on my setup, with X-Plane 10, in that, on the ground, the Ailerons / Rudder no longer suddenly flip to nearly full throw on the application of "5% aileron" with the keyboard.  The J and Keys   correctly move the ailerons and rudder in fly by wire mode with this patch applied.
Please can you test this change, on your PC  and let me know if the fix works for you.
I know that casting can be tricky, and that this change needs some careful reviewing. It may well effect any other ports to non dspic processors. …
=> SILSIM: Fix for FBW mode to operate correctly.

Tools/UDB_Logo_Editor/udb_logo_editor.html
I am going to ask Ric, to test this change. The returned angles were previously negative for headings between 270 degrees and due North. They are now positive values between zero and 360 degrees.
I have tested the following snippet which was previously faulty but now works correctly in the edtor:-
PEN_UP
USE_CURRENT_POSITION
IF_LT(ANGLE_TO_HOME, 180)
WEST(200)
ELSE
EAST(200)
END
The following also works correctly:-
IF_GT(REL_ANGLE_TO_HOME, 0)
WEST(300)
ELSE
EAST(300)
END
As shown in these two screenshots where the angle of the plane relative to the origin varies just slightly from just 0 degrees to just above 0 degrees.
=> UDB_Logo_Editor: Fix calculation of angles when using atan2().

libUDB/analog2digital_udb5.c
N.B. ADC_CLK formula is correct for udb4 and auav3 analog2digital_xxx files.
=> Replace MIPS by FCY to compute ADC_CLK.

MatrixPilot/flightplan-logo.c
Before this the number of instructions in interrupts could not exceed MAX_INSTRUCTIONS_PER_CYCLE.
Simply making MAX_INSTRUCTIONS_PER_CYCLE larger would cause 40(Hz) * x instructions per seconds
This fix: the first cycle will run the first MAX_INSTRUCTIONS_PER_CYCLE instructions,
but will continue with the next cycle to run the instructions that follow the first batch. If no CLEAR is encountered, the routine will run to its end and start over.
Interrupt routines are only run while the main program is waiting for a fly command to finish.
=> Fix to allow for bigger interrupt programs.

MatrixPilot/MAVParams.c, MatrixPilot/telemetry.c, MatrixPilot/telemetry_log.c, Tools/MatrixPilot-SIL/Makefile, Tools/MatrixPilot-SIL/SILcat.cpp
The main purpose of this PR is to ensure that SILSIM MatrixPilot, when compiled on a 64 bit mac or Unix machine, will store SUE telemetry correctly.  32 bit int32_t variables such as Latitude and Longitude were being printed incorrectly on 64 bit machines when the variables were negative, because the sign bit was not treated as a sign bit when they were 64 bit integers. The end result was the the Google Earth KMZ files for a demo flight in Innsbruck were flying out into space, and across russia when viewed in Google Earth. That should is now fixed.
At the same time, I have tried to remove all the compiler warnings under Ubuntu and most of the warnings under MacOS.  The PR requires further testing by myself at this stage. 
The end goal is to have SILSIM working well under Macos, Ubuntu and …
=> Ensure that SUE Telemetry works correctly with a 64bit word MatrixPilot

Config/options.h, MatrixPilot/helicalTurnCntrl.c, MatrixPilot/helicalTurnCntrl.h, MatrixPilot/telemetry.c, Tools/flight_analyzer/flan.pyw, Tools/flight_analyzer/matrixpilot_lib.py
I am ambivalent about adding these changes to master, as I have not seen much interest in them so far. But I'm going to post this Pull Request here for now, to see if anyone actually would like this facility.
This set of changes allows the effects of PID flight control gains to be analyzed in more detail; either using a csv file / spreadsheet, or using a [graphing tool within an inflight video. ](https://vimeo.com/264754315). I have used "racerenderer" and I could add the templates for racerender to pick up the data from the csv file, and to layout the graphs on the video. I think it is quite useful for seeing whether the Tilt error, Rate of rotation error, or Desired Rotation, or dynamic Trim, is responsible at any moment, for moving the ailerons, rudder or elevator.
I have tested this …
=> Flight control telemetry

MatrixPilot/flightplan-waypoints.c
When working on a landing flight plan at a soccer field for his Easystar, Bill discovered that on occasion there was a 1/40th of a second glitch in the interpolated calculation of desiredHeight only when a new waypoint was selected in Autonomous mode.  The interpolated desiredHeight becomes the new waypoint desiredHeight  for 1/40th of a second. i.e. desiredHeight  is not interpolated until the next flightcontrol frame runs, and there after everything is correct until the next waypoint is reached.
I have since replicated the bug in HILSIM which can be seen for every waypoint where the requested altitude is different (only seen consistently when telemetry is printed out at 40Hz).
This bug does not occur when using Logo, as the Logo code specifically re-calls …
=> flightplan-waypoints.c: Fix navigation glitch 
